name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    steps:
      - uses: actions/checkout@v3

      - name: Stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
